# Задание 1

In [1]:
import numpy as np
import pandas as pd
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

ser0 = pd.Series(mylist)
ser1 = pd.Series(myarr)
ser2 = pd.Series(mydict)
print(ser2)

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64


# Задание 2

In [7]:
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

df = pd.DataFrame(ser)
print(df[:10])

   0
a  0
b  1
c  2
e  3
d  4
f  5
g  6
h  7
i  8
j  9


# Задание 3

In [9]:
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
df = ser.reset_index()
df.columns=['Index','Value']
print(df)

   Index  Value
0      a      0
1      b      1
2      c      2
3      e      3
4      d      4
5      f      5
6      g      6
7      h      7
8      i      8
9      j      9
10     k     10
11     l     11
12     m     12
13     n     13
14     o     14
15     p     15
16     q     16
17     r     17
18     s     18
19     t     19
20     u     20
21     v     21
22     w     22
23     x     23
24     y     24
25     z     25


# Задание 4

In [11]:
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser0 = pd.Series(mylist)
ser1 = pd.Series(myarr)
df = pd.concat([ser0,ser1],axis=1)
df.columns = ['Column1','Column2']
print(df)

   Column1  Column2
0        a        0
1        b        1
2        c        2
3        e        3
4        d        4
5        f        5
6        g        6
7        h        7
8        i        8
9        j        9
10       k       10
11       l       11
12       m       12
13       n       13
14       o       14
15       p       15
16       q       16
17       r       17
18       s       18
19       t       19
20       u       20
21       v       21
22       w       22
23       x       23
24       y       24
25       z       25


# Задание 5

In [12]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser.name = 'latin_letters'
print(ser)

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
Name: latin_letters, dtype: object


# Задание 6

In [18]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
result = pd.concat([ser1[~ser1.isin(ser2)], ser2[~ser2.isin(ser1)]])
print(result)

0    1
1    2
2    3
2    6
3    7
4    8
dtype: int64


# Задание 7

In [11]:
ser = pd.Series(np.random.normal(10, 5, 25))


min_value = ser.min()
q25 = ser.quantile(0.25)
median = ser.median()
q75 = ser.quantile(0.75)
max_value = ser.max()


print(f"Минимальное значение: {min_value}")
print(f"25-й процентиль: {q25}")
print(f"Медиана: {median}")
print(f"75-й процентиль: {q75}")
print(f"Максимальное значение: {max_value}")

np.percentile(ser,q=[0,25,50,75,100])

Минимальное значение: -2.06956884968569
25-й процентиль: 5.421623551208695
Медиана: 10.279708682995606
75-й процентиль: 13.616703400231142
Максимальное значение: 19.249634464470848


array([-2.06956885,  5.42162355, 10.27970868, 13.6167034 , 19.24963446])

# Задание 8

In [21]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
print(ser.value_counts(normalize=True))

a    0.300000
d    0.166667
f    0.166667
c    0.100000
b    0.100000
h    0.066667
e    0.066667
g    0.033333
Name: proportion, dtype: float64


# Задание 9

In [10]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))


ser_modified = ser.map(lambda x: x if x in ser.value_counts().head(2).index else 'Прочее')



print("\nМодифицированная серия:")
print(ser_modified)


Модифицированная серия:
0          2
1     Прочее
2          4
3     Прочее
4          2
5     Прочее
6          4
7     Прочее
8          4
9          2
10    Прочее
11         2
dtype: object


# Задание 10

In [16]:
ser = pd.Series(np.random.random(20))
print(ser.head())

pd.qcut(ser, q = [0, .1, .2, .3, .4, .5, .6, .7, .8, .9, 1], labels = ['1th','2th','3th','4th','5th','6th','7th','8th','9th','10th']).head()

0    0.736968
1    0.728231
2    0.285314
3    0.705892
4    0.160251
dtype: float64


0    8th
1    8th
2    3th
3    7th
4    2th
dtype: category
Categories (10, object): ['1th' < '2th' < '3th' < '4th' ... '7th' < '8th' < '9th' < '10th']

# Задание 11

In [20]:
ser = pd.Series(np.random.randint(1, 10, 35))

df = pd.DataFrame(ser.values.reshape(7,5))
print(df)

   0  1  2  3  4
0  6  3  5  8  5
1  1  4  9  9  2
2  8  6  5  8  9
3  7  3  1  3  4
4  2  5  5  7  7
5  6  1  1  3  8
6  4  1  9  3  9


# Задание 12

In [23]:
ser = pd.Series(np.random.randint(1, 10, 7))
print(ser)
print(ser % 3 == 0)
np.argwhere(ser % 3 == 0)

0    7
1    6
2    9
3    4
4    3
5    4
6    5
dtype: int64
0    False
1     True
2     True
3    False
4     True
5    False
6    False
dtype: bool


array([[1],
       [2],
       [4]])

# Задание 13

In [30]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
print(ser.take(pos))
print([ser[x] for x in pos])

0     a
4     e
8     i
14    o
20    u
dtype: object
['a', 'e', 'i', 'o', 'u']


# Задание 14

In [35]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
df = pd.DataFrame({'0': ser1, '1': ser2})
print(df)

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


# Задание 15

In [36]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])
[np.where(i == ser1)[0].tolist() for i in ser2]

[[5], [4], [0], [8]]

# Задание 16

In [37]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)
np.mean((truth-pred)**2)

np.float64(0.24747118210320246)

# Задание 17

In [38]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
pd.Series(x.title() for x in ser)

0     How
1      To
2    Kick
3    Ass?
dtype: object

# Задание 18

In [40]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
pd.Series(len(x) for x in ser)

0    3
1    2
2    4
3    4
dtype: int64

# Задание 19

In [43]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])
print(ser.diff())
print(ser.diff().diff())

0    NaN
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    6.0
7    8.0
dtype: float64
0    NaN
1    NaN
2    1.0
3    1.0
4    1.0
5    1.0
6    0.0
7    2.0
dtype: float64


# Задание 20

In [5]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
ser_datetime = pd.to_datetime(ser,format='mixed')
print(ser_datetime)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]


# Задание 21

In [9]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
ser_datetime = pd.to_datetime(ser,format='mixed')
print(ser_datetime.dt.day.tolist())
print(ser_datetime.dt.isocalendar().week.tolist())
print(ser_datetime.dt.dayofyear.tolist())
print(ser_datetime.dt.day_name().tolist())

[1, 2, 3, 4, 5, 6]
[53, 5, 9, 14, 19, 23]
[1, 33, 63, 94, 125, 157]
['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


# Задание 22

In [10]:
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])
ser_datetime = pd.to_datetime(ser,format='mixed').apply(lambda x: x.replace(day=4))
print(ser_datetime)

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]


# Задание 23

In [11]:
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])
def count_vowels(word):
    vowels = 'aeiouAEIOU'
    return sum(1 for char in word if char in vowels)
fil_ser = ser[ser.apply(count_vowels) >= 2]
print(fil_ser)

0     Apple
1    Orange
4     Money
dtype: object


# Задание 24

In [16]:
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

import re 
mask = emails.map(lambda x: bool(re.match(pattern,x)))
print(emails[mask])

1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object


# Задание 25

In [24]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weights.tolist())
print(fruit.tolist())

df = pd.DataFrame({'fruit': fruit, 'weights':weights})
print(df.groupby('fruit')['weights'].mean())

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['carrot', 'apple', 'apple', 'apple', 'carrot', 'apple', 'banana', 'apple', 'banana', 'carrot']
fruit
apple     4.600000
banana    8.000000
carrot    5.333333
Name: weights, dtype: float64


# Задание 26

In [25]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

print(np.linalg.norm(p-q))

18.16590212458495


# Задание 27

In [27]:
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])
print(ser[(ser > ser.shift(1)) & (ser > ser.shift(-1))].index)


Index([1, 5, 7], dtype='int64')


# Задание 28

In [3]:
my_str = 'dbc deb abed gade'

char_series = pd.Series(list(my_str))

char_counts = char_series.value_counts()
least_frequent_char = char_counts.idxmin()

result = my_str.replace(' ', least_frequent_char)

print(result)

dbccdebcabedcgade


# Задание 29

In [6]:
dates = pd.date_range(start='2000-01-01', periods=10, freq='W-SAT')
val = np.random.randint(1,10,size=10)
print(pd.Series(data=val, index=dates))


2000-01-01    4
2000-01-08    8
2000-01-15    2
2000-01-22    4
2000-01-29    8
2000-02-05    9
2000-02-12    2
2000-02-19    5
2000-02-26    9
2000-03-04    4
Freq: W-SAT, dtype: int64


# Задание 30

In [19]:
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08'],format='mixed'))
print(ser)
full_range = pd.date_range(start=ser.index.min(),end=ser.index.max(),freq='D')
full_ser = ser.reindex(full_range)
print(full_ser.ffill())

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64
2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     3.0
Freq: D, dtype: float64


# Задание 31

In [12]:
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))
autocorr = [ser.autocorr(lag=i) for i in range(1, 11)]
max_corr_lag = np.argmax(autocorr)
print(f"values will change due to randomness {autocorr}")
print(f"Lag having highest correlation: {max_corr_lag}")

values will change due to randomness [np.float64(0.18057524844255377), np.float64(0.18056528413594866), np.float64(0.36416974468591756), np.float64(-0.02772415809647937), np.float64(0.20250415350626558), np.float64(0.46010716020396897), np.float64(-0.3295529356096082), np.float64(0.030780629217268013), np.float64(0.23064202866801894), np.float64(0.022739151223171016)]
Lag having highest correlation: 5


# Задание 32

In [17]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', skiprows=lambda x: x%50 != 0 and x!=0)
print(df)


      crim  zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.21977   0   6.91     0  0.448  5.602  62.0  6.0877    3  233     17.9   
1  0.06860   0   2.89     0  0.445  7.416  62.5  3.4952    2  276     18.0   
2  2.73397   0  19.58     0  0.871  5.597  94.9  1.5257    5  403     14.7   
3  0.03150  95   1.47     0  0.403  6.975  15.3  7.6534    3  402     17.0   
4  0.19073  22   5.86     0  0.431  6.718  17.5  7.8265    7  330     19.1   
5  0.05561  70   2.24     0  0.400  7.041  10.0  7.8278    5  358     14.8   
6  0.02899  40   1.25     0  0.429  6.939  34.5  8.7921    1  335     19.7   
7  9.91655   0  18.10     0  0.693  5.852  77.8  1.5004   24  666     20.2   
8  7.52601   0  18.10     0  0.713  6.417  98.3  2.1850   24  666     20.2   
9  0.17783   0   9.69     0  0.585  5.569  73.5  2.3999    6  391     19.2   

        b  lstat  medv  
0  396.90  16.20  19.4  
1  396.90   6.19  33.2  
2  351.85  21.45  15.4  
3  396.90   4.56  34.9  
4  393.74   6.56

# Задание 33

In [20]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', converters={'medv': lambda x: 'Low' if float(x) < 25 else 'High'})
print(df)

        crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98   Low  
1       17.8  396.90   9.14   Low  
2       17.8  3

# Задание 34

In [22]:
L = pd.Series(range(15))
result = np.array([L[i:i + 4].values for i in range(0, len(L) - 4 + 1, 2)])
print(result)

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]


# Задание 35

In [55]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', usecols = ['crim', 'medv'])
print(df.head())

      crim  medv
0  0.00632  24.0
1  0.02731  21.6
2  0.02729  34.7
3  0.03237  33.4
4  0.06905  36.2


# Задание 36

In [30]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
cnt_rows, cnt_cols = df.shape

np_arr = df.to_numpy().tolist()

print(cnt_rows)
print(cnt_cols)
print(df.dtypes[:10])
print(df.describe(include='all'))
print(np_arr[:10])


93
27
Manufacturer     object
Model            object
Type             object
Min.Price       float64
Price           float64
Max.Price       float64
MPG.city        float64
MPG.highway     float64
AirBags          object
DriveTrain       object
dtype: object
       Manufacturer    Model     Type  Min.Price      Price  Max.Price  \
count            89       92       90  86.000000  91.000000  88.000000   
unique           31       92        6        NaN        NaN        NaN   
top            Ford  Integra  Midsize        NaN        NaN        NaN   
freq              8        1       22        NaN        NaN        NaN   
mean            NaN      NaN      NaN  17.118605  19.616484  21.459091   
std             NaN      NaN      NaN   8.828290   9.724280  10.696563   
min             NaN      NaN      NaN   6.700000   7.400000   7.900000   
25%             NaN      NaN      NaN  10.825000  12.350000  14.575000   
50%             NaN      NaN      NaN  14.600000  17.700000  19.150000   


# Задание 37

In [62]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
max_price_row = df['Price'].idxmax()
manufacturer = df.at[max_price_row, 'Manufacturer']
model = df.at[max_price_row, 'Model']
type = df.at[max_price_row, 'Type']
price_col_num = df.columns.get_loc('Price')
print(f"Manufacturer: {manufacturer}, Model: {model}, Type: {type}")
print(f"Row number: {max_price_row}, Column number: {price_col_num}")

Manufacturer: Mercedes-Benz, Model: 300E, Type: Midsize
Row number: 58, Column number: 4


# Задание 38

In [32]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.columns)
df.rename(columns={'Type':'CarType'}, inplace=True)
df.columns = df.columns.str.replace('.','_')
print(df.columns)

Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
       'Make'],
      dtype='object')
Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


# Задание 39

In [36]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.isnull().sum().sum())

170


# Задание 40

In [41]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.isnull().sum())
print(df.isnull().sum().idxmax(), df.isnull().sum().max())

Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags               38
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64
AirBags 38


# Задание 41

In [43]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
mean_min_pr = df['Min.Price'].mean()
mean_max_pr = df['Max.Price'].mean()
df['Min.Price'].fillna(mean_min_pr, inplace=True)
df['Max.Price'].fillna(mean_max_pr, inplace=True)
print(df)

   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0   
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0   
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31

/var/folders/cw/fvky6lcd1fq2kp8_tfxlc3hw0000gn/T/ipykernel_78084/1676155840.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price'].fillna(mean_min_pr, inplace=True)
/var/folders/cw/fvky6lcd1fq2kp8_tfxlc3hw0000gn/T/ipykernel_78084/1676155840.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values alw

# Задание 42

In [47]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')


def missing(row, col1_mean, col2_median):
    if pd.isnull(row['Min.Price']):
        row['Min.Price'] = col1_mean
    if pd.isnull(row['Max.Price']):
        row['Max.Price'] = col2_median
    return row


min_pr_mean = df['Min.Price'].mean()
max_pr_median = df['Max.Price'].median()

df = df.apply(missing, axis=1, args=(min_pr_mean, max_pr_median))
print(df) 

   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9      18.80      25.0   
1           NaN   Legend  Midsize  29.200000   33.9      38.70      18.0   
2          Audi       90  Compact  25.900000   29.1      32.30      20.0   
3          Audi      100  Midsize  17.118605   37.7      44.60      19.0   
4           BMW     535i  Midsize  17.118605   30.0      19.15      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7      22.70      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0      22.40      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3      23.70      18.0   
91        Volvo      240  Compact  21.800000   22.7      23.50      21.0   
92          NaN      850  Midsize  24.800000   26.7      28.50      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31

# Задание 43

In [54]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
print(df)
print(df[['a']])

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
    a
0   0
1   5
2  10
3  15


# Задание 44

In [59]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
print(df)
df[['a','c']] = df[['c','a']]
print(df)

def swap_cols(df, col1, col2):
    df[[col1,col2]] = df[[col2,col1]]

swap_cols(df,'a','c')
print(df)

df = df.reindex(columns=sorted(df.columns, reverse=True))
print(df)

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
    a   b   c   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19
    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
    e   d   c   b   a
0   4   3   2   1   0
1   9   8   7   6   5
2  14  13  12  11  10
3  19  18  17  16  15


# Задание 45

In [63]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.iloc[:10, :10])

  Manufacturer       Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura     Integra    Small       12.9   15.9       18.8      25.0   
1          NaN      Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi          90  Compact       25.9   29.1       32.3      20.0   
3         Audi         100  Midsize        NaN   37.7       44.6      19.0   
4          BMW        535i  Midsize        NaN   30.0        NaN      22.0   
5        Buick     Century  Midsize       14.2   15.7       17.3      22.0   
6        Buick     LeSabre    Large       19.9   20.8        NaN      19.0   
7        Buick  Roadmaster    Large       22.6   23.7       24.9      16.0   
8        Buick     Riviera  Midsize       26.3   26.3       26.3      19.0   
9     Cadillac     DeVille    Large       33.0   34.7       36.3      16.0   

   MPG.highway             AirBags DriveTrain  
0         31.0                 NaN      Front  
1         25.0  Driver & Passenger      Front

# Задание 46

In [67]:
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])
print(df)
pd.options.display.float_format = '{:.4f}'.format
print(df)

   random
0  0.0020
1  0.0000
2  0.0007
3  0.0631
   random
0  0.0020
1  0.0000
2  0.0007
3  0.0631


# Задание 47

In [74]:
df = pd.DataFrame(np.random.random(4), columns=['random'])
df['random'] = df['random'].apply(lambda x: f'{x * 100:.2f}%')
print(df)

   random
0  51.54%
1  91.14%
2  51.10%
3   2.74%


# Задание 48

In [78]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.iloc[::20][['Manufacturer', 'Model', 'Type']])

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


# Задание 49

In [79]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna('missing')
df['index'] = df['Manufacturer'] + '_' + df['Model'] + '_' + df['Type']

df.set_index('index', inplace=True)
is_primary_key = df.index.is_unique

print(df)
print(is_primary_key)

                          Manufacturer    Model     Type  Min.Price  Max.Price
index                                                                         
Acura_Integra_Small              Acura  Integra    Small    12.9000    18.8000
missing_Legend_Midsize         missing   Legend  Midsize    29.2000    38.7000
Audi_90_Compact                   Audi       90  Compact    25.9000    32.3000
Audi_100_Midsize                  Audi      100  Midsize        NaN    44.6000
BMW_535i_Midsize                   BMW     535i  Midsize        NaN        NaN
...                                ...      ...      ...        ...        ...
Volkswagen_Eurovan_Van      Volkswagen  Eurovan      Van    16.6000    22.7000
Volkswagen_Passat_Compact   Volkswagen   Passat  Compact    17.6000    22.4000
Volkswagen_Corrado_Sporty   Volkswagen  Corrado   Sporty    22.9000    23.7000
Volvo_240_Compact                Volvo      240  Compact    21.8000    23.5000
missing_850_Midsize            missing      850  Mid

# Задание 50

In [199]:
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))
print(df)
print(df['a'].nlargest(5).index[-1])

    a   b   c
0  17  20   7
1  28  28  16
2  11  12  16
3  18  24  29
4  19  18  10
5   8  25  22
6   1  24  23
7  27  13   1
8  11  14  19
9   6  17  26
0


# Задание 51

In [197]:
ser = pd.Series(np.random.randint(1, 100, 15))
print(ser)
print(ser[ser > ser.mean()].nlargest(2).index[-1])

0      2
1     65
2     93
3     75
4     69
5     92
6     27
7      1
8     48
9      9
10    43
11    27
12    98
13    94
14    17
dtype: int64
13


# Задание 52

In [94]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
print(df[-2:][df.sum(axis=1) > 100]) 
# если мы должны брать последние две строки не из общего случая и при выполнении условия
# их выводить, то следует поменять [][] местами
# тк задание можно трактовать по разному

     0   1   2   3
13  18  38  19  37


/var/folders/cw/fvky6lcd1fq2kp8_tfxlc3hw0000gn/T/ipykernel_78084/4107166136.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(df[-2:][df.sum(axis=1) > 100])


# Задание 53

In [98]:
ser = pd.Series(np.logspace(-2, 2, 30))
print(ser.to_list())
print(ser.clip(lower=np.percentile(ser, 5), upper=np.percentile(ser, 95)).to_list())

[0.01, 0.01373823795883263, 0.018873918221350976, 0.02592943797404667, 0.035622478902624426, 0.04893900918477494, 0.06723357536499334, 0.09236708571873861, 0.12689610031679222, 0.17433288221999882, 0.2395026619987486, 0.32903445623126676, 0.4520353656360243, 0.6210169418915616, 0.8531678524172805, 1.1721022975334805, 1.6102620275609392, 2.212216291070448, 3.039195382313198, 4.175318936560401, 5.736152510448681, 7.880462815669913, 10.82636733874054, 14.873521072935118, 20.433597178569418, 28.072162039411758, 38.56620421163472, 52.98316906283707, 72.78953843983146, 100.0]
[0.016049294076965887, 0.016049294076965887, 0.018873918221350976, 0.02592943797404667, 0.035622478902624426, 0.04893900918477494, 0.06723357536499334, 0.09236708571873861, 0.12689610031679222, 0.17433288221999882, 0.2395026619987486, 0.32903445623126676, 0.4520353656360243, 0.6210169418915616, 0.8531678524172805, 1.1721022975334805, 1.6102620275609392, 2.212216291070448, 3.039195382313198, 4.175318936560401, 5.73615251

# Задание 54

In [102]:
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10, -1))


df = df[df >= 0].dropna(how='all')
pos_vals = df.values[df >= 0].flatten()

n = int(np.sqrt(len(pos_vals)))

pos_vals = pos_vals[:n * n]

square_df = pd.DataFrame(pos_vals.reshape(n, n))
print(square_df)

        0       1       2       3       4       5       6       7
0 41.0000 19.0000  2.0000 46.0000 28.0000 22.0000 12.0000  1.0000
1 35.0000  1.0000 17.0000  2.0000 19.0000 23.0000 39.0000 16.0000
2 33.0000  4.0000 33.0000 46.0000 17.0000 23.0000 32.0000 48.0000
3  9.0000 47.0000  9.0000 48.0000 10.0000 25.0000 35.0000 30.0000
4 45.0000 20.0000 43.0000 24.0000 32.0000 13.0000 22.0000 26.0000
5 38.0000 27.0000 35.0000 35.0000 22.0000 48.0000  5.0000  4.0000
6 37.0000 18.0000  3.0000 21.0000 10.0000 34.0000 39.0000  0.0000
7 40.0000 29.0000  4.0000  9.0000 27.0000 34.0000 34.0000  2.0000


# Задание 55

In [103]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))
print(df)

df.iloc[[1, 2]] = df.iloc[[2, 1]].values
print(df)


    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
    0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24


# Задание 56

In [105]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))
print(df.iloc[::-1].reset_index(drop=True))

    0   1   2   3   4
0  20  21  22  23  24
1  15  16  17  18  19
2  10  11  12  13  14
3   5   6   7   8   9
4   0   1   2   3   4


# Задание 57

In [113]:
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))

binary_columns = pd.get_dummies(df['a'])
binary_columns = binary_columns.astype(int)

df = pd.concat([binary_columns, df[['b', 'c', 'd', 'e']]], axis=1)
print(df)

   0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24


# Задание 58

In [163]:
df = pd.DataFrame(np.random.randint(1, 100, 40).reshape(10, -1))
print(df)

max_cnt = df.apply(lambda x: (x == x.max()).sum())

print(max_cnt.idxmax())

    0   1   2   3
0  14  96  66  44
1  36  95  83  80
2  63   8  82  75
3  86  12  26  11
4  90  45  42  26
5  92  70  45  97
6  82  85  36   4
7  87  45  14  83
8  60  61  69  69
9  13  37  62  72
0


# Задание 59

In [169]:
df = pd.DataFrame(np.random.randint(1, 100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))
from scipy.spatial.distance import cdist
distances = cdist(df, df, metric='euclidean')

near_rows = np.argmin(distances + np.eye(distances.shape[0]) * np.inf, axis=1)
df['nearest_row'] = df.index[near_rows]
df['dist'] = [distances[i, near_rows[i]] for i in range(len(df))]
print(df)

    p   q   r   s nearest_row     dist
a   2  85  29  45           b  66.6783
b  48  37  24  46           a  66.6783
c  48  25  25  28           a  77.5951
d  76  25  50  81           a 103.9856
e  90  37  10   8           a 108.5265
f  47  51  89  40           a  82.4985
g  37  74  99  37           a  79.4355
h  57  87  84  51           a  78.0385
i  84   9  75  36           a 121.2312
j  29  92  85  90           a  77.0649


/var/folders/cw/fvky6lcd1fq2kp8_tfxlc3hw0000gn/T/ipykernel_78084/1359325262.py:5: RuntimeWarning: invalid value encountered in multiply
  near_rows = np.argmin(distances + np.eye(distances.shape[0]) * np.inf, axis=1)


# Задание 60

In [190]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))

max_corr = df.corr().abs()
np.fill_diagonal(max_corr.values, np.nan)


print(max_corr.max())

p   0.8047
q   0.6011
r   0.7516
s   0.6602
t   0.8047
u   0.5862
v   0.8176
w   0.8176
x   0.5862
y   0.4374
dtype: float64


# Задание 61

In [196]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
print(pd.DataFrame({'mn': df.min(axis=1), 'mx': df.max(axis=1)}))

   mn  mx
0   3  96
1   6  90
2  12  85
3   4  99
4   4  92
5   8  97
6   2  95
7   2  82


# Задание 62

In [202]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
df['penultimate'] = df.apply(lambda row: row.nlargest(2).iloc[-1], axis=1)
print(df)

    0   1   2   3   4   5   6   7   8   9  penultimate
0  52  93  90  80  39  61  82  60  30  17           90
1   1  21  52  41  91  20  85  59  17  59           85
2  37  23  42  56  60  50  49  18   5   3           56
3  76  42  85  51  50   5  28  10  76  81           81
4  82  34  30  61  61  10  28   4  65  71           71
5  28   5  89  68  59  83  91  37  75  23           89
6   3   7  99  22  28  99  65  41  93  70           99
7   1  51  81  23  69  85  89  90  65   3           89


# Задание 63

In [203]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

df_norm = (df - df.mean()) / df.std()
df_rank = (df - df.min()) / (df.max() - df.min())

print(df_norm)
print(df_rank)

        0       1       2       3       4       5       6       7       8  \
0 -1.4097  1.5355 -1.3774  0.5619  0.1750  1.0374  0.1891 -0.1330  0.3832   
1  0.1575 -1.2337  0.1704  0.0723  0.8927 -1.1451  0.0656  1.5762  1.0122   
2 -1.1946 -0.3107  1.0549 -1.3519  1.0363 -0.8005  0.6523 -0.4878  1.1694   
3 -0.4264 -0.7722  0.8338  1.3630 -2.1219 -0.7430 -1.3857 -1.2940  0.8549   
4  1.0794  0.2929 -0.1981  0.1613  0.6056  0.3482  1.2082 -0.1653 -1.3201   
5  0.3419 -1.0207 -1.3774  0.6954 -0.3993 -0.9153 -0.2123 -1.0360 -0.8222   
6  1.4481  1.0385  1.1286 -1.5744 -0.2557  1.1235 -1.4784  1.1569 -0.1409   
7  0.0038  0.4704 -0.2349  0.0723  0.0673  1.0948  0.9611  0.3830 -1.1366   

        9  
0  0.5620  
1  1.8588  
2 -0.1729  
3 -0.9078  
4 -0.1297  
5  0.0432  
6 -1.5130  
7  0.2594  
       0      1      2      3      4      5      6      7      8      9
0 0.0000 1.0000 0.0000 0.7273 0.7273 0.9620 0.6207 0.4045 0.6842 0.6154
1 0.5484 0.0000 0.6176 0.5606 0.9545 0.0000 0.5747 1.0

# Задание 64

In [205]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

df_shift = df.shift(-1)
corr = df.corrwith(df_shift)

print(corr)

0   -0.3148
1   -0.0878
2   -0.6462
3    0.4882
4   -0.4031
5    0.4423
6   -0.3774
7    0.3826
8   -0.1484
9   -0.5280
dtype: float64


# Задание 65

In [206]:
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))
np.fill_diagonal(df.values, 0)
for i in range(df.shape[0]):
    df.iloc[i, df.shape[1] - i - 1] = 0

print(df)

    0   1   2   3   4   5   6   7   8   9
0   0  26  93  34  31   2  86  67  64   0
1  48   0  32  66  70   3  21  68   0  86
2  58   6   0  30  54   1  28   0  83   6
3  87  68  24   0  57  91   0  58  38  54
4  67  55  60  44   0   0  27  45  70  23
5  25  22  81  84   0   0  23  78  35  34
6  18  20  15   0  29  49   0  69  88  60
7  31  84   0  53  12  69  22   0  27  85
8  98   0  75  34  73  23  56  69   0  82
9   0  45  80  19  80  28  15  16  66   0


# Задание 66

In [207]:
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})

df_grouped = df.groupby(['col1'])
apple_group = df_grouped.get_group('apple')

print(apple_group)

    col1   col2  col3
0  apple 0.6360    13
3  apple 0.4204     9
6  apple 0.9076    11


/var/folders/cw/fvky6lcd1fq2kp8_tfxlc3hw0000gn/T/ipykernel_78084/1286414787.py:6: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  apple_group = df_grouped.get_group('apple')


# Задание 67

In [209]:
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'taste': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

banana_df = df[df['fruit'] == 'banana']
top_2_banana = banana_df['taste'].nlargest(2).iloc[-1]
print(df)
print(top_2_banana)

    fruit  taste  price
0   apple 0.0435      6
1  banana 0.1092      9
2  orange 0.1096     14
3   apple 0.5977      7
4  banana 0.8745      3
5  orange 0.3542      5
6   apple 0.6523      7
7  banana 0.3837      3
8  orange 0.6981      0
0.3837201476344714


# Задание 68

In [210]:
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

print(df.groupby('fruit')['price'].mean().reset_index())

    fruit  price
0   apple 8.0000
1  banana 5.3333
2  orange 6.0000


# Задание 69

In [213]:
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

merged_df = pd.merge(df1, df2, how='inner', left_on=['fruit', 'weight'], right_on=['pazham', 'kilo'])

print(merged_df)

    fruit weight  price_x  pazham  kilo  price_y
0   apple   high        1   apple  high        4
1  orange    low        2  orange   low       12
2   apple   high       11   apple  high        4
3  orange    low        6  orange   low       12
4   apple   high       11   apple  high        4
5  orange    low        0  orange   low       12


# Задание 70

In [214]:
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))

df['a_lag1'] = df['a'].shift(1)  
df['b_lead1'] = df['b'].shift(-1)  

print(df)

    a   b   c   d  a_lag1  b_lead1
0  25  30  88  65     NaN  79.0000
1  23  79  88  26 25.0000  91.0000
2   1  91  31  94 23.0000  92.0000
3  17  92  51  54  1.0000  64.0000
4   1  64  13  72 17.0000      NaN


# Задание 71

In [216]:
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns=list('abcd'))

un = df.apply(pd.Series.value_counts)
print(df)
print(un)

   a  b  c  d
0  8  5  7  7
1  3  3  8  8
2  1  5  1  9
3  7  3  7  7
4  2  7  5  3
       a      b      c      d
1 1.0000    NaN 1.0000    NaN
2 1.0000    NaN    NaN    NaN
3 1.0000 2.0000    NaN 1.0000
5    NaN 2.0000 1.0000    NaN
7 1.0000 1.0000 2.0000 2.0000
8 1.0000    NaN 1.0000 1.0000
9    NaN    NaN    NaN 1.0000


# Задание 72

In [217]:
df = pd.DataFrame(["STD, City    State",
                   "33, Kolkata    West Bengal",
                   "44, Chennai    Tamil Nadu",
                   "40, Hyderabad    Telengana",
                   "80, Bangalore    Karnataka"], columns=['row'])

df_split = df['row'].str.split(r',\s*|\s{2,}', expand=True)
df_split.columns = ['STD', 'City', 'State']

print(df_split)

   STD       City        State
0  STD       City        State
1   33    Kolkata  West Bengal
2   44    Chennai   Tamil Nadu
3   40  Hyderabad    Telengana
4   80  Bangalore    Karnataka
